// Package sitemap refuses a sitemap that disagrees with the pages the build
// wrote.
//
// The file is generated, so on the day it is written the two agree by
// construction and a check over them proves nothing. What this refuses is the
// day after. A page written by something that runs after the list is assembled,
// or beside the flow that assembles it, lands in the output and is named
// nowhere: the build is green, the page is served, and the only party who finds
// out is a crawler that is never told to ask for it.
//
// The other direction is the one that is worse to serve. An address listed with
// no page behind it sends every client that reads the list to the not-found
// page, repeatedly, and the site is the party claiming the address exists.
//
// It walks the output rather than reading the list of paths the build reported,
// so what it compares is the file on disk against the files on disk. A walk that
// trusted the writer's own account of what it wrote would agree with the writer
// about a page the writer never mentioned.
package sitemap

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/Flowfin/site/internal/site"
)

// location is one address a sitemap states. The file is generated by this
// repository and read by clients that accept far less than a parser would, so
// this reads the one element it is about rather than the document around it: a
// sitemap this build did not write is not a case that arises, and a whole XML
// reader here would be apparatus nobody maintains.
var location = regexp.MustCompile(`(?is)<loc>\s*([^<]*?)\s*</loc>`)

// Listed returns the addresses a sitemap states, in the order it states them.
func Listed(body []byte) []string {
	var out []string
	for _, m := range location.FindAllSubmatch(body, -1) {
		out = append(out, string(m[1]))
	}
	return out
}

// Decide returns one detail per disagreement between what a sitemap lists and
// what the produced pages are owed, in the order each side was given.
//
// Three things are refused and each names what it costs a reader, because the
// two directions fail for opposite reasons and a failure saying only that the
// two lists differ leaves the next person to work out which way round it is.
func Decide(listed, owed []string) []string {
	have := map[string]int{}
	for _, l := range listed {
		have[l]++
	}
	want := map[string]bool{}
	for _, o := range owed {
		want[o] = true
	}

	var details []string
	for _, o := range owed {
		if have[o] == 0 {
			details = append(details, fmt.Sprintf(
				"the build produced a page served at %s and %s lists no entry for it, so nothing ever tells a crawler the page is there",
				o, site.SitemapPath))
		}
	}
	reported := map[string]bool{}
	for _, l := range listed {
		switch {
		case !want[l] && !reported[l]:
			reported[l] = true
			details = append(details, fmt.Sprintf(
				"%s lists %s, and the build wrote no page served at that address, so a crawler following it is answered with the not-found page",
				site.SitemapPath, l))
		case want[l] && have[l] > 1 && !reported[l]:
			reported[l] = true
			details = append(details, fmt.Sprintf(
				"%s lists %s %d times, and one page listed twice is one page fetched twice by everything that reads the file",
				site.SitemapPath, l, have[l]))
		}
	}
	return details
}

// Run builds the tree at root into a directory it throws away and compares the
// sitemap it finds there against the pages beside it.
func Run(root string, log io.Writer) error {
	tmp, err := os.MkdirTemp("", "site-sitemap-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	out := filepath.Join(tmp, site.OutputDir)
	if _, err := site.Build(root, out, io.Discard); err != nil {
		return fmt.Errorf("the build refused, so there is nothing to compare: %w", err)
	}

	produced, err := walk(out)
	if err != nil {
		return err
	}
	owed := site.SitemapAddresses(produced)

	body, err := os.ReadFile(filepath.Join(out, filepath.FromSlash(site.SitemapPath)))
	switch {
	case os.IsNotExist(err) && len(owed) == 0:
		fmt.Fprintf(log, "sitemap: the build produced no page and no %s, so this leg examined nothing\n", site.SitemapPath)
		return nil
	case os.IsNotExist(err):
		fmt.Fprintf(log, "sitemap: 0 address(es) listed, against %d page(s) the build produced\n", len(owed))
		fmt.Fprintf(log, "  the build wrote %d page(s) and no %s, so nothing lists any of them\n", len(owed), site.SitemapPath)
		return fmt.Errorf("sitemap: %d page(s) are listed nowhere", len(owed))
	case err != nil:
		return err
	}

	listed := Listed(body)
	details := Decide(listed, owed)

	fmt.Fprintf(log, "sitemap: %d address(es) listed, against %d page(s) the build produced\n", len(listed), len(owed))
	if len(details) > 0 {
		for _, d := range details {
			fmt.Fprintf(log, "  %s\n", d)
		}
		return fmt.Errorf("sitemap: %d disagreement(s) between the list and the output", len(details))
	}
	fmt.Fprintf(log, "  every page the build wrote is listed once, and every entry has a page behind it\n")
	return nil
}

// walk returns every file under out, named the way the host serves it. It is a
// walk of the directory rather than of what the build said it wrote, which is
// the whole point of this leg.
func walk(out string) ([]string, error) {
	var found []string
	err := filepath.WalkDir(out, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(out, p)
		if err != nil {
			return err
		}
		found = append(found, strings.TrimPrefix(filepath.ToSlash(rel), "./"))
		return nil
	})
	return found, err
}
