// Package invariant holds the rules about this repository that a machine can
// decide by reading bytes, and refuses a tree that breaks one.
//
// A rule is one row. A row carries the population it reads, the reason it
// exists, what it refuses, and the code that decides it. Adding a rule is adding
// a row, and nothing else changes.
//
// The rows live here rather than in the workflow that reports them. A rule
// written as a shell block in a workflow file has no suite that can prove it
// bites and no way to run it on the machine where the mistake was made, which is
// the position this repository already took for the commit message rules. What
// the workflow supplies is the name the result reports under.
//
// A run says what it examined, and it also says what it did not. Three of the
// rules this gate is meant to carry have nothing in the tree to read yet, and
// they are printed as owed with the issue that lands what they would read. A run
// that listed only the rows it could decide would read as a tree that satisfies
// all of them.
package invariant

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/Flowfin/site/internal/site"
)

// The populations a row can read. A row names one of them, and the run reads
// each population once however many rows ask for it.
const (
	// ProducedPages is every HTML file the build just wrote.
	ProducedPages = "every page the build produced"
	// ProducedFiles is everything the build just wrote, markup or not.
	ProducedFiles = "every file the build produced"
	// TrackedText is every tracked file that is not binary, except the file
	// that declares the marker vocabulary. That exclusion is real and is
	// stated rather than hidden: a file listing the strings a rule refuses
	// would be refused by its own rule, and the alternative is a vocabulary
	// spelled in fragments, which nobody can read or maintain.
	TrackedText = "every tracked text file, except the one declaring the vocabulary"
	// TestSources is every tracked test source. The headless rule is a rule
	// about what the suite does, so it reads the suite.
	TestSources = "every tracked test source"
)

// vocabularyFile is the path excluded from TrackedText, and it is derived from
// nothing: it is this file. A rule that guessed at its own path would stop
// excluding it the day the package moved.
const vocabularyFile = "internal/invariant/invariant.go"

// Rule is one invariant.
type Rule struct {
	ID      string
	Subject string
	Reason  string
	Refuses string
	// decide returns one detail per violation in body, or nothing.
	decide func(body []byte) []string
}

// Owed is a rule this gate is meant to carry and cannot yet, because what it
// would read is not in the tree. It is printed by every run.
type Owed struct {
	ID      string
	Waiting string
}

var (
	htmlElement  = regexp.MustCompile(`(?is)<html\b[^>]*>`)
	langAttr     = regexp.MustCompile(`(?is)\blang\s*=\s*"([^"]*)"`)
	titleElement = regexp.MustCompile(`(?is)<title\b[^>]*>(.*?)</title>`)
	scriptSrc    = regexp.MustCompile(`(?is)<script\b[^>]*\bsrc\s*=`)
	unfinished   = regexp.MustCompile(`TODO|FIXME`)
)

// markers is the vocabulary the tool-marker rule refuses, lower-cased. It is a
// floor rather than a guarantee: it holds the shapes that actually leak, and it
// will not catch one nobody has written yet.
var markers = []string{
	"generated by chatgpt",
	"generated by copilot",
	"generated by an ai",
	"generated with claude",
	"co-authored-by: claude",
	"this file was generated by an assistant",
}

// Rules is the table. The order is the order a run reports them in.
func Rules() []Rule {
	return []Rule{
		{
			ID:      "page-declares-its-language",
			Subject: ProducedPages,
			Reason:  "a page with no language is read aloud in whichever one the reader's software guessed, and the guess is wrong for exactly the readers who depend on it",
			Refuses: "a produced page with no html element, or one whose lang attribute is missing or empty",
			decide:  decideLang,
		},
		{
			ID:      "page-carries-a-title",
			Subject: ProducedPages,
			Reason:  "the title is what a search result, a tab and a shared link show, so a page without one is a page nobody can tell apart from another",
			Refuses: "a produced page with no title element, or one holding only whitespace",
			decide:  decideTitle,
		},
		{
			ID:      "page-fetches-no-script",
			Subject: ProducedPages,
			Reason:  "the budget puts required scripting at zero bytes, and a script element with a source is a request this site did not have to make and a party that learns who is reading",
			Refuses: "a produced page carrying a script element with a src attribute, wherever it points",
			decide:  decideScriptSrc,
		},
		{
			ID:      "output-carries-no-unfinished-marker",
			Subject: ProducedFiles,
			Reason:  "a note to the author is a note to every reader once it is served, and it is the kind of thing nobody greps for after the fact",
			Refuses: "a produced file containing TODO or FIXME",
			decide:  decideUnfinished,
		},
		{
			ID:      "tracked-text-names-no-tool",
			Subject: TrackedText,
			Reason:  "a marker naming what produced a file says nothing about the file and outlives every reason it was written, and removing one after it has landed rewrites history rather than editing a line",
			Refuses: "a tracked text file carrying one of the produced-by markers in the vocabulary",
			decide:  decideMarkers,
		},
		{
			ID:      "test-opens-no-window",
			Subject: TestSources,
			Reason:  "a suite that needs a screen is a suite that is run rarely, and a suite that is run rarely is not a gate",
			Refuses: "a test source naming a driver that opens a window or drives a real browser",
			decide:  literal(windowDrivers, "names a driver that opens a window"),
		},
		{
			ID:      "test-needs-no-display-server",
			Subject: TestSources,
			Reason:  "a test that reaches for a display passes on the machine it was written on and fails on every runner, and the failure reads as a broken test rather than as a broken assumption",
			Refuses: "a test source naming a display server or the variable that points at one",
			decide:  literal(displayServers, "names a display server"),
		},
		{
			ID:      "test-binds-only-loopback",
			Subject: TestSources,
			Reason:  "binding a machine's own interface address rather than loopback is what makes a desktop firewall ask an administrator for permission, and that dialog is answered per executable path, so answering it settles nothing for the next build directory",
			Refuses: "a listen address in a test source whose host is neither loopback nor absent by being loopback",
			decide:  decideBind,
		},
		{
			ID:      "test-writes-no-certificate-store",
			Subject: TestSources,
			Reason:  "a certificate store is machine-wide state, so a test that writes one changes the machine for everything else on it and asks for elevation on the way",
			Refuses: "a test source naming a tool that installs or trusts a certificate",
			decide:  literal(certificateStores, "names a tool that writes a certificate store"),
		},
		{
			ID:      "test-asks-for-no-elevation",
			Subject: TestSources,
			Reason:  "elevation does not fail as a red test but as a consent prompt that takes the screen away from whoever was working, and a test that does that once is a test people learn to skip",
			Refuses: "a test source naming a way to ask for administrator or root",
			decide:  pattern(elevation, "asks for elevation"),
		},
		{
			ID:      "test-needs-nothing-outside-the-toolchain",
			Subject: TestSources,
			Reason:  "a package that is neither in the toolchain nor part of this module is a thing somebody has to install before the suite runs, and a suite with a setup step is a suite that is run rarely",
			Refuses: "an import in a test source that is neither standard library nor inside this module",
			decide:  decideImports,
		},
	}
}

// The vocabularies the headless rows read. Each is a floor rather than a
// guarantee: it holds the shapes that actually arrive, and it will not catch one
// nobody has written yet. They are declared here, in the file already excluded
// from the tracked-text population, so no row refuses the list it reads from.
var (
	windowDrivers = []string{
		"github.com/chromedp/chromedp",
		"github.com/go-rod/rod",
		"github.com/playwright-community/playwright-go",
		"github.com/tebeka/selenium",
		"github.com/webview/webview",
		"fyne.io/fyne",
	}
	displayServers = []string{
		"xvfb",
		"wayland_display",
		`"display"`,
		"display=:",
	}
	certificateStores = []string{
		"dev-certs",
		"certutil",
		"add-trusted-cert",
		"update-ca-certificates",
		"cert:\\localmachine",
	}
	// modulePath is this module, and an import under it is this repository
	// rather than something to install.
	modulePath = "github.com/Flowfin/site"
)

var (
	elevation  = regexp.MustCompile(`(?i)\b(sudo|gsudo|pkexec|runas|netsh|schtasks|sc\.exe)\b|-verb\s+runas`)
	listenCall = regexp.MustCompile(`(?s)Listen[A-Za-z]*\(\s*(?:"[a-z0-9]+"\s*,\s*)?"([^"]*)"`)
	importLine = regexp.MustCompile(`(?m)^\s*(?:_\s+|\.\s+|[a-zA-Z0-9_]+\s+)?"([^"]+)"\s*$`)
)

// literal returns a decide that refuses any of the vocabulary, compared
// lower-cased so a capitalisation does not walk through.
func literal(vocabulary []string, detail string) func([]byte) []string {
	return func(body []byte) []string {
		lower := bytes.ToLower(body)
		var details []string
		for _, v := range vocabulary {
			at := 0
			for {
				i := bytes.Index(lower[at:], []byte(v))
				if i < 0 {
					break
				}
				at += i
				details = append(details, fmt.Sprintf("line %d %s", lineOf(body, at), detail))
				at += len(v)
			}
		}
		return details
	}
}

// pattern returns a decide that refuses every match of re.
func pattern(re *regexp.Regexp, detail string) func([]byte) []string {
	return func(body []byte) []string {
		var details []string
		for _, loc := range re.FindAllIndex(body, -1) {
			details = append(details, fmt.Sprintf("line %d %s", lineOf(body, loc[0]), detail))
		}
		return details
	}
}

// decideBind reads the address a listen call was given. An empty host means
// every interface on the machine, which is the shape that raises the prompt, so
// it is refused as loudly as a written-out address.
func decideBind(body []byte) []string {
	var details []string
	for _, m := range listenCall.FindAllSubmatchIndex(body, -1) {
		addr := string(body[m[2]:m[3]])
		host := addr
		if i := strings.LastIndex(addr, ":"); i >= 0 {
			host = addr[:i]
		}
		host = strings.Trim(host, "[]")
		switch strings.ToLower(host) {
		case "127.0.0.1", "localhost", "::1":
			continue
		case "":
			details = append(details, fmt.Sprintf("line %d binds %q, which is every interface on the machine rather than loopback", lineOf(body, m[0]), addr))
		default:
			details = append(details, fmt.Sprintf("line %d binds %q, which is not loopback", lineOf(body, m[0]), addr))
		}
	}
	return details
}

// decideImports refuses an import that is neither standard library nor inside
// this module. A standard library path has no dot in its first element, which is
// the rule the toolchain itself uses to tell the two apart.
func decideImports(body []byte) []string {
	var details []string
	for _, m := range importLine.FindAllSubmatchIndex(body, -1) {
		p := string(body[m[2]:m[3]])
		first := p
		if i := strings.Index(p, "/"); i >= 0 {
			first = p[:i]
		}
		if !strings.Contains(first, ".") {
			continue
		}
		if p == modulePath || strings.HasPrefix(p, modulePath+"/") {
			continue
		}
		details = append(details, fmt.Sprintf("line %d imports %s, which is neither standard library nor inside this module", lineOf(body, m[0]), p))
	}
	return details
}

// Owing is what this gate is meant to refuse and cannot decide yet. Each entry
// names what has to exist first. Printed by every run, passing or not.
func Owing() []Owed {
	return []Owed{
		{
			ID:      "page-carries-the-affiliation-notice",
			Waiting: "the notice itself, in #51. No produced page carries one today, so a row added now would refuse every page for the absence of a sentence nobody has written",
		},
		{
			ID:      "tree-references-no-domain-outside-the-allowlist",
			Waiting: "the allowlist, in #37. decisions/0011-what-this-site-will-never-do.md names the position and points at that issue for the refusal; no list of permitted domains exists in this tree to compare against",
		},
		{
			ID:      "design-tokens-live-in-exactly-one-file",
			Waiting: "the token file, in #65 and #66. There is no token in this tree, so the rule would compare one absent file against another",
		},
	}
}

// Run decides every rule against the tree at root and writes what it examined
// to log. It builds the site into a directory it throws away, so what the page
// rules read is what a build produces rather than whatever is sitting in the
// output directory from an earlier one.
func Run(root string, log io.Writer) error {
	rules := Rules()
	ids := make([]string, len(rules))
	for i, r := range rules {
		ids[i] = r.ID
	}
	fmt.Fprintf(log, "invariants: %d rule(s), in order: %s\n", len(rules), strings.Join(ids, ", "))

	populations, err := gather(root)
	if err != nil {
		return err
	}

	refused := 0
	for _, r := range rules {
		files, ok := populations[r.Subject]
		if !ok {
			return fmt.Errorf("rule %s reads %q, which is not a population this run gathered", r.ID, r.Subject)
		}
		var details []string
		for _, f := range files {
			for _, d := range r.decide(f.body) {
				details = append(details, fmt.Sprintf("%s: %s", f.name, d))
			}
		}
		if len(details) > 0 {
			refused++
			fmt.Fprintf(log, "  %s: REFUSED, %d violation(s)\n", r.ID, len(details))
			fmt.Fprintf(log, "    it refuses %s\n", r.Refuses)
			fmt.Fprintf(log, "    because %s\n", r.Reason)
			for _, d := range details {
				fmt.Fprintf(log, "    %s\n", d)
			}
			continue
		}
		if len(files) == 0 {
			fmt.Fprintf(log, "  %s: %s held no file, so this rule examined nothing\n", r.ID, r.Subject)
			continue
		}
		fmt.Fprintf(log, "  %s: ok, %d file(s) of %s\n", r.ID, len(files), r.Subject)
	}

	for _, o := range Owing() {
		fmt.Fprintf(log, "  %s: not decided, waiting on %s\n", o.ID, o.Waiting)
	}

	fmt.Fprintf(log, "%d rule(s) decided, %d owed and not decided.\n", len(rules), len(Owing()))
	if refused > 0 {
		return fmt.Errorf("invariants: %d rule(s) refused this tree", refused)
	}
	return nil
}

type file struct {
	name string
	body []byte
}

// gather reads each population once. The build goes into a temporary directory
// so that a run leaves nothing behind that a reader might mistake for the result
// of `go run . build`.
func gather(root string) (map[string][]file, error) {
	tmp, err := os.MkdirTemp("", "site-invariants-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tmp)

	out := filepath.Join(tmp, site.OutputDir)
	written, err := site.Build(root, out, io.Discard)
	if err != nil {
		return nil, fmt.Errorf("the build refused, so there is no output to read: %w", err)
	}
	if len(written) == 0 {
		return nil, fmt.Errorf("the build wrote no file, and there is nothing to decide a page rule against")
	}

	// The build labels what it wrote with the output directory it was given,
	// and it was given an absolute one so that nothing lands beside a
	// reader's real output. Names are reported back as if it had been the
	// tree's own dist/, because that is the path a person opens.
	label := filepath.ToSlash(out) + "/"

	var produced, pages []file
	for _, w := range written {
		rel := strings.TrimPrefix(filepath.ToSlash(w), label)
		b, err := os.ReadFile(filepath.Join(out, filepath.FromSlash(rel)))
		if err != nil {
			return nil, err
		}
		f := file{name: path.Join(site.OutputDir, rel), body: b}
		produced = append(produced, f)
		if strings.HasSuffix(rel, ".html") {
			pages = append(pages, f)
		}
	}

	tracked, tests, err := trackedText(root)
	if err != nil {
		return nil, err
	}

	return map[string][]file{
		ProducedPages: pages,
		ProducedFiles: produced,
		TrackedText:   tracked,
		TestSources:   tests,
	}, nil
}

// trackedText reads every tracked file that is not binary, and separates out the
// test sources. It asks git rather than walking, because the rule is about what
// this repository carries and a walk also reads whatever happens to be sitting in
// the working directory.
func trackedText(root string) ([]file, []file, error) {
	cmd := exec.Command("git", "ls-files", "-z")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return nil, nil, fmt.Errorf("listing the tracked files: %w", err)
	}

	var text, tests []file
	for _, name := range strings.Split(strings.TrimRight(string(out), "\x00"), "\x00") {
		if name == "" {
			continue
		}
		b, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if err != nil {
			if os.IsNotExist(err) {
				// A tracked path that is not in the working tree is a
				// checkout somebody is in the middle of, not a violation.
				continue
			}
			return nil, nil, err
		}
		if bytes.IndexByte(b, 0) >= 0 {
			continue
		}
		f := file{name: name, body: b}
		if strings.HasSuffix(name, "_test.go") {
			tests = append(tests, f)
		}
		if name != vocabularyFile {
			text = append(text, f)
		}
	}
	return text, tests, nil
}

func decideLang(body []byte) []string {
	el := htmlElement.Find(body)
	if el == nil {
		return []string{"there is no html element on this page"}
	}
	m := langAttr.FindSubmatch(el)
	if m == nil {
		return []string{"the html element carries no lang attribute"}
	}
	if strings.TrimSpace(string(m[1])) == "" {
		return []string{"the lang attribute on the html element is empty"}
	}
	return nil
}

func decideTitle(body []byte) []string {
	m := titleElement.FindSubmatch(body)
	if m == nil {
		return []string{"there is no title element on this page"}
	}
	if strings.TrimSpace(string(m[1])) == "" {
		return []string{"the title element holds only whitespace"}
	}
	return nil
}

func decideScriptSrc(body []byte) []string {
	var details []string
	for _, loc := range scriptSrc.FindAllIndex(body, -1) {
		details = append(details, fmt.Sprintf("line %d carries a script element with a src attribute", lineOf(body, loc[0])))
	}
	return details
}

func decideUnfinished(body []byte) []string {
	var details []string
	for _, loc := range unfinished.FindAllIndex(body, -1) {
		details = append(details, fmt.Sprintf("line %d carries %s", lineOf(body, loc[0]), body[loc[0]:loc[1]]))
	}
	return details
}

func decideMarkers(body []byte) []string {
	lower := bytes.ToLower(body)
	var details []string
	for _, m := range markers {
		at := 0
		for {
			i := bytes.Index(lower[at:], []byte(m))
			if i < 0 {
				break
			}
			at += i
			details = append(details, fmt.Sprintf("line %d names a tool that produced it", lineOf(body, at)))
			at += len(m)
		}
	}
	return details
}

// lineOf is one-based, so a detail reads like something a person can open.
func lineOf(body []byte, at int) int {
	return bytes.Count(body[:at], []byte("\n")) + 1
}
